"use strict";

export const SET_CODE = "SET_CODE";

export const SET_LANGUAGE = "SET_LANGUAGE";

export const SET_SNIPPET_CLEAR_ON_EDIT = "SET_SNIPPET_CLEAR_ON_EDIT";

export const TOGGLE_LANGUAGE_SELECT = "TOGGLE_LANGUAGE_SECLECT";

export const SET_APP_FULLY_LOADED = "SET_APP_FULLY_LOADED";

